
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www
    ports:
      - "80:80"  # Mở port 80 trên máy host và ánh xạ vào container
      - "8000:8000"  # Mở port 8000 để chạy Laravel development server
    volumes:
      - .:/var/www/html  # Ánh xạ thư mục hiện tại vào thư mục web của Apache trong container
    depends_on:
      - db  # Đảm bảo container PHP khởi động sau container MySQL

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root  # Mật khẩu cho root user
      MYSQL_DATABASE: laravel  # Tên database mặc định
      MYSQL_USER: laravel  # Tên người dùng
      MYSQL_PASSWORD: secret  # Mật khẩu người dùng
    ports:
      - "3306:3306"  # Mở port MySQL cho container
    volumes:
      - mysql-data:/var/lib/mysql  # Dung lượng lưu trữ dữ liệu MySQL

volumes:
  mysql-data:  # Khai báo volume cho dữ liệu MySQL
