services:
  - type: web
    name: web-cham-cong
    env: docker
    plan: free
    region: oregon
    healthCheckPath: /
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d155i5h5pdvs73etl6e0-a
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: web_cham_cong
      - key: DB_USERNAME
        value: web_cham_cong_user
      - key: DB_PASSWORD
        sync: false
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_DRIVER
        value: file
      - key: VIEW_COMPILED_PATH
        value: /tmp
      - key: SESSION_PATH
        value: /tmp/sessions
      - key: CACHE_PATH
        value: /tmp/cache
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan key:generate
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
      php artisan migrate --force
    startCommand: php artisan serve --host=0.0.0.0 --port=$PORT
    autoDeploy: true

databases:
  - name: laravel-db
    databaseName: web_cham_cong
    user: web_cham_cong_user
