services:
  - type: web
    name: web-cham-cong
    env: docker
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        value: ${LARAVEL_APP_KEY}
      - key: APP_URL
        value: https://web-cham-cong.onrender.com
      - key: DATABASE_URL
        fromDatabase: laravel-db
      - key: LOG_CHANNEL
        value: stderr
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: FILESYSTEM_DISK
        value: local
      - key: DB_CONNECTION
        value: pgsql
    healthCheckPath: /
    autoDeploy: true

databases:
  - name: laravel-db
    databaseName: web_cham_cong
    user: web_cham_cong_user
